In [2]:
import torch

torch.__version__
torch.Tensor

torch.Tensor

In [3]:
scalar = torch.tensor(7)
print(scalar, scalar.ndim, scalar.item())

tensor(7) 0 7


In [4]:
vector = torch.tensor([7, 7])
print(vector, vector.ndim, vector.shape)

tensor([7, 7]) 1 torch.Size([2])


In [5]:
matrix = torch.tensor([[7, 8], [9, 10]])
print(matrix, matrix.ndim, matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]]) 2 torch.Size([2, 2])


In [6]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor, tensor.ndim, tensor.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 3 torch.Size([1, 3, 3])


In [7]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.2102, 0.7410, 0.6212, 0.0074],
        [0.7289, 0.0868, 0.0392, 0.9154],
        [0.7216, 0.4576, 0.5057, 0.9021]])

In [8]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
arange = torch.arange(0, 10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
ten_zeros = torch.zeros_like(arange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.half)
float_16_tensor.dtype

torch.float16

In [12]:
some_tensor = torch.rand(3, 4)

print(
    some_tensor,
    some_tensor.ndim,
    some_tensor.shape,
    some_tensor.dtype,
    some_tensor.device,
)

tensor([[0.7631, 0.3143, 0.8478, 0.1776],
        [0.0976, 0.3814, 0.8839, 0.7346],
        [0.3814, 0.1329, 0.3988, 0.1733]]) 2 torch.Size([3, 4]) torch.float32 cpu


In [13]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10, tensor * 10)

tensor([11, 12, 13]) tensor([10, 20, 30])


In [14]:
torch.mul(tensor, 2)

tensor([2, 4, 6])

In [15]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [16]:
print(tensor * tensor, torch.matmul(tensor, tensor), tensor @ tensor)
# @ not recomended

tensor([1, 4, 9]) tensor(14) tensor(14)


In [17]:
tensor = torch.arange(0, 9).reshape((3, 3))
tensor

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [21]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)

x = torch.arange(1, 7).reshape((3, 2)).float()
ouptput = linear(x)

ouptput

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [28]:
tensor = torch.rand(3, 4)
tensor_16 = tensor.type(torch.float16)
tensor

tensor([[0.6057, 0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578, 0.3313],
        [0.3227, 0.0162, 0.2137, 0.6249]])

In [45]:
x = torch.arange(1.0, 8.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [39]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [46]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [60]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [61]:
torch.squeeze(x)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [65]:
x.unsqueeze(dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [66]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))